name: Update mini 1.0

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta el workflow una vez al día a la medianoche
  workflow_dispatch:

jobs:
  auto-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PA_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "1nfinit0"
          git config --global user.email "noggnzzz@gmail.com"

      - name: Pull changes
        run: |
          git pull --rebase origin master  

      - name: Run random count script
        run: |
          python random_push.py

      - name: Read count from file
        id: read_count
        run: |
          echo "count=$(cat count.txt)" >> $GITHUB_ENV

      - name: Add and commit changes
        run: |
          git add .
          git commit -m "Lasted update"
          echo "Commits made: ${{ env.count }}"

      - name: Push changes multiple times
        run: |
          git push origin master
