name: Auto Commit and Push

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta el workflow una vez al día a la medianoche
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde GitHub

jobs:
  auto-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          # Usar el token de acceso personal
          token: ${{ secrets.PA_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "1nfinit0"
          git config --global user.email "noggnzzz@gmail.com"

      - name: Run random count script
        run: |
          python random_push.py

      - name: Read count from file
        id: read_count
        run: |
          echo "count=$(cat count.txt)" >> $GITHUB_ENV

      - name: Add and commit changes
        run: |
          git add .
          git commit -m "Auto-commit"
          echo "Commits made: ${{ env.count }}"

      - name: Pull changes
        run: |
          git pull --rebase origin master  

      - name: Push changes multiple times
        run: |
          git push origin master
